### ISSUE TITLE
WdfRequestRetrieveUnsafeUserOutputBuffer doesn't return IRP::UserBuffer for METHOD_BUFFERED

### ISSUE THREAD

**Issue by OZ1** [microsoft/Windows-Driver-Frameworks#18] opened 2021-10-22 20:49 UTC
MSDN doc ([here](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_irp)) says that `IRP::UserBuffer` _"Contains the address of an output buffer if ... The I/O control code was defined with METHOD_NEITHER **or** **METHOD_BUFFERED**"_. However `WdfRequestRetrieveUnsafeUserOutputBuffer` returns `STATUS_INVALID_DEVICE_REQUEST` unless IOCTL's method is `METHOD_NEITHER`.

**Comment by wm1** [comment] 2022-05-29 01:37
By design and won't fix. IRP fields and WDF API are not one-to-one mapping.

For buffered I/O, while IRP UserBuffer points to a buffer, MSDN clearly says that it is used by I/O manager internally and driver should not touch it. Thus, there is no reason for WDF to provide an API that returns a pointer but then tell driver authors to not use it.

The WdfRequestRetrieveUnsafeUserOutputBuffer clearly says it only wants to deal with neither IO. The failure as you described is the expected behavior.

**Closed by wm1** 2022-05-29 01:37 UTC
